### ISSUE TITLE
Implement voxel descriptor feature extraction

### ISSUE THREAD

**Issue by darrenwee** [darrenwee/drug-discovery#1]
Implement a (simplified) version of the voxel feature extraction

Ref: https://github.com/Acellera/htmd/blob/master/htmd/molecule/voxeldescriptors.py

> Both protein and ligand are featurized via a voxelized 24 Å representation of the binding site considering eight pharmacophoric-like properties.

Jiménez, J., Skalic, M., Martínez-Rosell, G., & De Fabritiis, G. (2018). K DEEP: Protein–Ligand Absolute Binding Affinity Prediction via 3D-Convolutional Neural Networks. Journal of chemical information and modeling, 58(2), 287-296.

**Comment by alexfjw** [comment]
Note that the mapping in `def _getRadii(mol):` is quite incomplete. 
I edited the mappings to fill up the missing matches. 

Also, there's a divide by zero error at line 330. I did a quick hack on my side to avoid that problem. (Both the 'C' implementation & numba implementation suffer from this problem. The numba implementation was easier to fix.) 
https://github.com/Acellera/htmd/blob/330655f6d03a56efe6909c041fb65c5a7ce5ea23/htmd/molecule/voxeldescriptors.py#L330

See following link for the edited file. https://gist.github.com/alexfjw/c49980f7053f1e0b225581e5f410d7f2
